### ISSUE TITLE
"any" is not exported by the List::Util module

### ISSUE THREAD

**Issue by trquinn** [hainest/ChaNGa_test#2]
I'm getting:
perl ./build.pl
"any" is not exported by the List::Util module
Can't continue after import errors at ./build.pl line 106.
BEGIN failed--compilation aborted at ./build.pl line 106.

My guess is that I have an old version of perl:
perl --version

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 33 registered patches, see perl -V for more detail)

**Comment by hainest** [comment]
Sorry, I didn't see you submitted this. It looks like List::Util::any was added in v1.33 of the module. You can use `sudo cpan -D List::Util` to see your currently installed version and `sudo cpan -i List::Util` to get the latest version. I will add that as a note in the requirements (once those are published). If we have old perls on clusters, then I'll probably have to include the module in this repo.
