### ISSUE TITLE
Can't locate Configure.pm 

### ISSUE THREAD

**Issue by trquinn** [hainest/ChaNGa_test#4]
I do: "perl build.pl", and I get:
Can't locate Configure.pm in @INC (you may need to install the Configure module) (@INC contains: /sw/contrib/perl/5.26.2/lib/site_perl/5.26.2/x86_64-linux-thread-multi /sw/contrib/perl/5.26.2/lib/site_perl/5.26.2 /sw/contrib/perl/5.26.2/lib/5.26.2/x86_64-linux-thread-multi /sw/contrib/perl/5.26.2/lib/5.26.2) at build.pl line 6.
BEGIN failed--compilation aborted at build.pl line 6.

This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

**Comment by hainest** [comment]
That's weird. The pwd should be in @INC by default. Which machine gave you this error?

**Comment by trquinn** [comment]
OS:  CentOS Linux release 7.4.1708 (Core)
Perl:
 perl -v

 perl -v

This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

Copyright 1987-2018, Larry Wall
This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

Copyright 1987-2018, Larry Wall

**Comment by hainest** [comment]
Oh, sorry, I meant the name of the machine. Is this a national SC, a local cluster, your personal machine, etc.?

**Comment by trquinn** [comment]
This is a UW local cluster.
