### ISSUE TITLE
--no-mpi option

### ISSUE THREAD

**Issue by trquinn** [hainest/ChaNGa_test#7]
A common use case is a simple multicore workstation where MPI isn't installed.  I assume in this case that the MPI::Simple perl module will also not be available.  Can there be an option to disable loading this module?

**Comment by hainest** [comment]
This should be fixed by f7c7be25261f6ccd6d2df2368c05518538253a18

**Comment by hainest** [comment]
Fixed by 9e942d8dab804f59701600767bcb4096726a7af8
