### ISSUE TITLE
Unrecognized mpicc options

### ISSUE THREAD

**Issue by trquinn** [hainest/ChaNGa_test#8]
Trouble compiling on Piz Daint:

trq@daint101:~/src/ChaNGa_test> make MPICC=cc
gcc: error: unrecognized command line option '--showme:incdirs'
gcc: error: unrecognized command line option '--showme:version'; did you mean '--no-version'?
trq@daint101:~/src/ChaNGa_test> gcc -v
Using built-in specs.
COLLECT_GCC=/opt/gcc/6.2.0/bin/../snos/bin/gcc
COLLECT_LTO_WRAPPER=/opt/gcc/6.2.0/snos/libexec/gcc/x86_64-suse-linux/6.2.0/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../cray-gcc-6.2.0/configure --prefix=/opt/gcc/6.2.0/snos --disable-nls --libdir=/opt/gcc/6.2.0/snos/lib --enable-languages=c,c++,fortran --with-gxx-include-dir=/opt/gcc/6.2.0/snos/include/g++ --with-slibdir=/opt/gcc/6.2.0/snos/lib --with-system-zlib --enable-shared --enable-__cxa_atexit --build=x86_64-suse-linux --with-ppl --with-cloog --disable-multilib
Thread model: posix
gcc version 6.2.0 20160822 (Cray Inc.) (GCC)

**Comment by hainest** [comment]
Should be fixed by adbc67c78958c5bca4c352d5dc7a8028c2761812

**Comment by hainest** [comment]
I just noticed that there is another place where this will fail. I've switched to an autotools-based build to make things easier in 9e942d8dab804f59701600767bcb4096726a7af8.

I also updated the README with more detailed instructions on how to build with and without MPI.

**Comment by hainest** [comment]
Fixed by 9e942d8dab804f59701600767bcb4096726a7af8
