### ISSUE TITLE
Undefined subroutine &ChaNGa::Util::copy_dir called at ./build.pl line 127.

### ISSUE THREAD

**Issue by trquinn** [hainest/ChaNGa_test#9]
For some reason ChaNGa was not being built.  I put a print in the "catch" clause at build.pl, line 272, and it gave the error in the subject line.

This is for
perl -v
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 33 registered patches, see perl -V for more detail)

**Comment by hainest** [comment]
That is quite bizarre as it is definitely there and has a default exported definition in case `File::Copy::Recursive` isn't available. Could you check

1. that `ChaNGa.pm` in the same directory as `build.pl`?

2. for other missing imports by running perl in debug mode (perl -D)

I will add logging in that catch statement so errors don't get swallowed.

**Comment by trquinn** [comment]
ChaNGa.pm is indeed in the same directory.

perl isn't compiled with DEBUG, so "-D" is operable.

**Comment by hainest** [comment]
I'm at a bit of a loss. Could you verify that the exports are happening on line 31 of ChaNGa.pm?

**Comment by trquinn** [comment]
ChaNGa.pm doesn't get past:
                        require List::MoreUtils;

**Comment by hainest** [comment]
It looks like you might have a bad pull. Try grabbing HEAD again.

**Comment by trquinn** [comment]
It looks like those "require"s in ChaNGa.pm need to be wrapped with an eval.  As it stands, the ChaNGa.pm load stops at "require List::MoreUtils;", and after I fix that, it stops at "require File::Copy::Recursive;"

**Comment by hainest** [comment]
List::Util::Any was added in 2013, but it looks like the perls you have are from 2012. I didn't anticipate running this on anything before 5.18, so I assumed that the first check wouldn't fail.

>It looks like those "require"s in ChaNGa.pm need to be wrapped with an eval.

The whole outer block is in an eval and using recursive evals is contraindicated. Let me re-write the default cases first so that the fail cases don't prevent usage.

**Comment by hainest** [comment]
Should be fixed in e7f6c93126f8ec8f5b5201c6ef388e6ac1a4f34f.

**Comment by trquinn** [comment]
I had to make the following patch to get things to work.

diff --git a/build.pl b/build.pl
index 3685ac2..c371d49 100644
--- a/build.pl
+++ b/build.pl
@@ -124,7 +124,7 @@ sub build_changa {
        make_path($dest);
        
        use ChaNGa::Util qw(copy_dir);
-       copy_dir("$args{'changa-dir'}/../utility/structures", "$dest/structures"
+       copy_dir("$args{'changa-dir'}/../utility/structures/.", "$dest/structure
        execute("cd $dest/structures && make clean 2>&1 >/dev/null");
 
        my $begin = Benchmark->new();

**Comment by hainest** [comment]
Is this on a Unix OS?

**Comment by trquinn** [comment]
CentOS 7

**Comment by hainest** [comment]
Fixed by a combination of e7f6c93126f8ec8f5b5201c6ef388e6ac1a4f34f and 680e4ce3b73b936f972eed50de470018b9a58e02.
